baseURL = 'https://217149.github.io/ZPC_Test1/'
languageCode = 'cs-cz'
title = 'My New Hugo Site'
theme = "ananke"

[pagination]
  pagerSize = 10

relativeURLs = true
enableGitInfo = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Domů"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "O nás"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "galerie"
    name = "Galerie"
    url = "/galerie/"
    weight = 3