baseURL = 'https://217149.github.io/ZPC_Test1/'
languageCode = 'cs-cz'
title = 'My New Hugo Site'
theme = "ananke"

relativeURLs = true

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/posts/"
  weight = 2